# not tested yet
version: "3.9"

networks:
  my-local-network:
    name: my-local-network

volumes:
  db:
    driver: local

services:
  wso2:
    # image: docker.wso2.com/wso2am:4.1.0.41-alpine
    image: wso2/wso2am:4.1.0-alpine
    container_name: "wso2"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8280:8280"
      - "8243:8243"
      - "9443:9443"
    networks:
      - my-local-network
    volumes:
      - ./configuration/deployment.toml:/home/wso2carbon/wso2am-4.1.0/repository/conf/deployment.toml
      # - ./SSL/my-keystore-tls.jks:/home/wso2carbon/wso2am-4.1.0/repository/resources/security/my-keystore-tls.jks
